language: node_js
node_js:
  - '4'
script: "chmod +x ./ci.sh; ./ci.sh"
env:
  global:
    - CI_NODE_TOTAL=4
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2
    - CI_NODE_INDEX=3