sudo: required
dist: trusty
language: node_js
node_js:
  - '4'
addons:
  apt:
    packages:
      - gnome-keyring
      - libgnome-keyring-dev
script: "chmod +x ./ci-travis.sh; ./ci-travis.sh"
cache:
  directories:
    - node_modules
env:
  global:
    - CI_NODE_TOTAL=5
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2
    - CI_NODE_INDEX=3
    - CI_NODE_INDEX=4
after_success:
  - npm run report-coverage